"""
Simulator Engine — paper trading engine that:
1. Hooks into the existing signal pipeline (_async_scan)
2. Filters signals through learning-adjusted thresholds
3. Opens SimulatedPositions in the DB
4. Monitors open positions for TP/SL/expiry hits
5. Triggers learning updates after closings
6. Generates daily journal entries at 22:00 UTC
"""

from datetime import date, datetime, timedelta, timezone

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.app.core.scalper.loss_learning import categorize_loss
from backend.app.core.scalper.signal_store import get_signals
from backend.app.core.simulator.learning import (
    get_or_create_active_state,
    update_learning_state,
)
from backend.app.database import async_session
from backend.app.logging_config import get_logger
from backend.app.models.daily_journal import DailyJournal
from backend.app.models.learning_state import LearningState
from backend.app.models.simulated_position import (
    PositionDirection,
    PositionStatus,
    SimulatedPosition,
)

logger = get_logger("simulator.engine")

# Symbols to simulate
SIM_SYMBOLS = [
    "XAUUSD", "BTCUSD", "ETHUSD",
    "EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD", "NZDUSD", "USDCHF",
]

# Expiry windows per timeframe family
EXPIRY_HOURS = {
    "5m": 6,
    "15m": 12,
    "30m": 24,
    "1h": 48,
    "1d": 72,
}


async def run_simulation_cycle():
    """
    Main simulation cycle — called every 5 minutes from background loop.

    1. Load active learning state
    2. Retrieve latest signals from Redis (generated by existing _async_scan)
    3. Filter through learning thresholds → open SimulatedPositions
    4. Monitor open positions for TP/SL/expiry
    5. Update learning state if positions were closed
    6. Generate daily journal at end of day
    """
    async with async_session() as db:
        try:
            state = await get_or_create_active_state(db)
            await db.commit()
        except Exception as e:
            await db.rollback()
            logger.error("learning_state_load_error", error=str(e))
            return

    # Phase A: Open new positions from recent signals
    opened = 0
    for symbol in SIM_SYMBOLS:
        try:
            count = await _process_signals_for_symbol(symbol)
            opened += count
        except Exception as e:
            logger.warning("sim_signal_process_error", symbol=symbol, error=str(e))

    # Phase B: Monitor and close open positions
    closed = 0
    try:
        closed = await _monitor_open_positions()
    except Exception as e:
        logger.error("sim_monitor_error", error=str(e))

    # Phase C: Update learning state if we had closures
    if closed > 0:
        async with async_session() as db:
            try:
                await update_learning_state(db)
                await db.commit()
            except Exception as e:
                await db.rollback()
                logger.error("learning_update_error", error=str(e))

    # Phase D: End-of-day journal check (22:00 UTC)
    now_utc = datetime.now(timezone.utc)
    if now_utc.hour == 22 and now_utc.minute < 6:
        try:
            await _create_daily_journal(now_utc.date())
        except Exception as e:
            logger.error("journal_create_error", error=str(e))

    if opened > 0 or closed > 0:
        logger.info(
            "simulation_cycle_complete",
            positions_opened=opened,
            positions_closed=closed,
        )


async def _process_signals_for_symbol(symbol: str) -> int:
    """
    Retrieve latest signals from Redis for a symbol, filter through
    learning thresholds, and create SimulatedPositions for qualifying signals.
    """
    # Get signals from Redis (generated by existing _async_scan pipeline)
    signals = get_signals(symbol=symbol, status="active") + get_signals(
        symbol=symbol, status="pending"
    )
    if not signals:
        return 0

    async with async_session() as db:
        state = await get_or_create_active_state(db)
        skip_regimes = set(state.skip_regimes or [])
        min_conf = state.min_confidence
        min_score = state.min_composite_score
        min_confl = state.min_confluence

        opened = 0
        for sig in signals:
            try:
                # Dedup: always check if this signal is already tracked
                entry = sig.get("entry_price", 0)
                tf = sig.get("timeframe", "")
                direction_str = sig.get("direction", "long").lower()
                existing = await db.execute(
                    select(SimulatedPosition.id).where(
                        SimulatedPosition.symbol == symbol,
                        SimulatedPosition.entry_price == entry,
                        SimulatedPosition.timeframe == tf,
                        SimulatedPosition.direction == (
                            PositionDirection.LONG if direction_str == "long"
                            else PositionDirection.SHORT
                        ),
                        SimulatedPosition.status == PositionStatus.OPEN,
                    ).limit(1)
                )
                if existing.scalar_one_or_none() is not None:
                    continue

                # Apply learning filters
                confidence = sig.get("confidence", 0)
                composite_score = sig.get("composite_score", 0)
                confluence = sig.get("confluence_count", 0)
                if not confluence:
                    reasons = sig.get("signal_reasons", {})
                    if isinstance(reasons, dict):
                        confluence = reasons.get("confluence_count", 0)

                regime = sig.get("regime_at_signal", sig.get("regime", ""))
                if regime in skip_regimes:
                    continue
                if confidence < min_conf:
                    continue
                if composite_score < min_score:
                    continue
                if confluence < min_confl:
                    continue

                # Determine expiry
                if not tf:
                    tf = "1d"
                expiry_h = EXPIRY_HOURS.get(tf, 24)
                now = datetime.now(timezone.utc)

                direction = (
                    PositionDirection.LONG
                    if direction_str == "long"
                    else PositionDirection.SHORT
                )

                pos = SimulatedPosition(
                    symbol=symbol,
                    timeframe=tf,
                    direction=direction,
                    status=PositionStatus.OPEN,
                    entry_price=float(sig.get("entry_price", 0)),
                    stop_loss=float(sig.get("stop_loss", 0)),
                    take_profit=float(sig.get("take_profit", 0)),
                    risk_reward_ratio=float(sig.get("risk_reward_ratio", 0)),
                    confidence=float(confidence),
                    composite_score=float(composite_score),
                    ml_confidence=sig.get("ml_confidence"),
                    regime=regime or None,
                    signal_reasons=sig.get("signal_reasons", {}),
                    indicator_snapshot=sig.get("indicator_snapshot", {}),
                    mtf_confluence=bool(sig.get("mtf_confluence", False)),
                    learning_version=state.version,
                    opened_at=now,
                    expires_at=now + timedelta(hours=expiry_h),
                )
                db.add(pos)
                opened += 1

            except Exception as e:
                logger.warning(
                    "sim_position_create_error",
                    symbol=symbol,
                    error=str(e),
                )

        if opened > 0:
            await db.commit()
            logger.info("sim_positions_opened", symbol=symbol, count=opened)

    return opened


async def _monitor_open_positions() -> int:
    """
    Check all open SimulatedPositions against latest prices.
    Close positions that hit TP, SL, or have expired.
    """
    async with async_session() as db:
        result = await db.execute(
            select(SimulatedPosition).where(
                SimulatedPosition.status == PositionStatus.OPEN
            )
        )
        open_positions = list(result.scalars().all())

        if not open_positions:
            return 0

        # Batch-fetch latest prices for all open symbols in one query
        symbols = set(p.symbol for p in open_positions)
        latest_prices = await _batch_get_latest_prices(db, symbols)

        now = datetime.now(timezone.utc)
        closed_count = 0

        for pos in open_positions:
            price_data = latest_prices.get(pos.symbol)
            if not price_data:
                # Check expiry even without price
                if pos.expires_at and now > pos.expires_at:
                    pos.status = PositionStatus.EXPIRED
                    pos.closed_at = now
                    closed_count += 1
                continue

            current = price_data["close"]
            high = price_data["high"]
            low = price_data["low"]

            # Update MFE / MAE
            if pos.direction == PositionDirection.LONG:
                favorable = high - pos.entry_price
                adverse = pos.entry_price - low
            else:
                favorable = pos.entry_price - low
                adverse = high - pos.entry_price

            pos.max_favorable = max(pos.max_favorable or 0, favorable)
            pos.max_adverse = max(pos.max_adverse or 0, adverse)

            # Check TP hit
            tp_hit = False
            sl_hit = False

            if pos.direction == PositionDirection.LONG:
                if high >= pos.take_profit:
                    tp_hit = True
                if low <= pos.stop_loss:
                    sl_hit = True
            else:
                if low <= pos.take_profit:
                    tp_hit = True
                if high >= pos.stop_loss:
                    sl_hit = True

            if tp_hit:
                pos.status = PositionStatus.WIN
                pos.exit_price = pos.take_profit
                pos.pnl = abs(pos.take_profit - pos.entry_price)
                pos.pnl_pct = (pos.pnl / pos.entry_price) * 100
                pos.closed_at = now
                closed_count += 1
                logger.info(
                    "sim_position_win",
                    symbol=pos.symbol,
                    pnl=f"{pos.pnl:.2f}",
                    pnl_pct=f"{pos.pnl_pct:.3f}%",
                )

            elif sl_hit:
                pos.status = PositionStatus.LOSS
                pos.exit_price = pos.stop_loss
                pos.pnl = -abs(pos.stop_loss - pos.entry_price)
                pos.pnl_pct = (pos.pnl / pos.entry_price) * 100
                pos.closed_at = now

                # Categorize the loss
                sig_dict = _position_to_signal_dict(pos)
                analysis = categorize_loss(sig_dict)
                pos.loss_category = analysis.get("category")
                pos.loss_analysis = analysis

                closed_count += 1
                logger.info(
                    "sim_position_loss",
                    symbol=pos.symbol,
                    pnl=f"{pos.pnl:.2f}",
                    category=pos.loss_category,
                )

            elif pos.expires_at and now > pos.expires_at:
                pos.status = PositionStatus.EXPIRED
                pos.closed_at = now
                closed_count += 1

        await db.commit()

    return closed_count


async def _batch_get_latest_prices(
    db: AsyncSession, symbols: set[str]
) -> dict[str, dict]:
    """
    Batch-fetch the latest OHLCV candle for each symbol using a single session.
    Tries 5m first, then 15m, then 1h.
    """
    from backend.app.models.asset import Asset
    from backend.app.models.ohlcv import OHLCVData, Timeframe

    if not symbols:
        return {}

    # Load all assets in one query
    result = await db.execute(
        select(Asset).where(Asset.symbol.in_([s.upper() for s in symbols]))
    )
    assets = {a.symbol: a for a in result.scalars().all()}

    prices: dict[str, dict] = {}
    for symbol in symbols:
        asset = assets.get(symbol.upper())
        if not asset:
            continue
        for tf in (Timeframe.M5, Timeframe.M15, Timeframe.H1):
            row_result = await db.execute(
                select(OHLCVData)
                .where(OHLCVData.asset_id == asset.id, OHLCVData.timeframe == tf)
                .order_by(OHLCVData.timestamp.desc())
                .limit(1)
            )
            row = row_result.scalar_one_or_none()
            if row:
                prices[symbol] = {
                    "close": float(row.close),
                    "high": float(row.high),
                    "low": float(row.low),
                    "timestamp": row.timestamp,
                }
                break

    return prices


def _position_to_signal_dict(pos: SimulatedPosition) -> dict:
    """Convert a SimulatedPosition to a signal-like dict for loss_learning."""
    return {
        "direction": pos.direction.value,
        "entry_price": pos.entry_price,
        "stop_loss": pos.stop_loss,
        "take_profit": pos.take_profit,
        "regime_at_signal": pos.regime or "unknown",
        "signal_reasons": pos.signal_reasons or {},
        "indicator_snapshot": pos.indicator_snapshot or {},
        "max_favorable": pos.max_favorable or 0,
        "max_adverse": pos.max_adverse or 0,
    }


async def _create_daily_journal(journal_date: date):
    """
    Aggregate all closed positions for the given date into a DailyJournal entry.
    """
    async with async_session() as db:
        # Check if journal already exists for this date
        existing = await db.execute(
            select(DailyJournal).where(DailyJournal.date == journal_date)
        )
        if existing.scalar_one_or_none():
            return  # Already generated

        # Query all positions closed today
        day_start = datetime.combine(journal_date, datetime.min.time()).replace(
            tzinfo=timezone.utc
        )
        day_end = day_start + timedelta(days=1)

        result = await db.execute(
            select(SimulatedPosition).where(
                SimulatedPosition.closed_at >= day_start,
                SimulatedPosition.closed_at < day_end,
                SimulatedPosition.status.in_([
                    PositionStatus.WIN,
                    PositionStatus.LOSS,
                    PositionStatus.EXPIRED,
                ]),
            )
        )
        closed_today = list(result.scalars().all())

        if not closed_today:
            return  # Nothing to journal

        wins = [p for p in closed_today if p.status == PositionStatus.WIN]
        losses = [p for p in closed_today if p.status == PositionStatus.LOSS]
        expired = [p for p in closed_today if p.status == PositionStatus.EXPIRED]
        decided = wins + losses  # Exclude expired from win rate

        win_rate = len(wins) / len(decided) * 100 if decided else 0.0
        pnls = [p.pnl or 0 for p in decided]
        total_pnl = sum(pnls)

        symbols_traded = sorted(set(p.symbol for p in closed_today))
        confidences = [p.confidence for p in closed_today if p.confidence]
        rr_ratios = [p.risk_reward_ratio for p in closed_today if p.risk_reward_ratio]

        # Regime breakdown
        regime_breakdown: dict[str, int] = {}
        for p in closed_today:
            regime = p.regime or "unknown"
            regime_breakdown[regime] = regime_breakdown.get(regime, 0) + 1

        # Get active learning version
        state_result = await db.execute(
            select(LearningState)
            .where(LearningState.is_active.is_(True))
            .limit(1)
        )
        active_state = state_result.scalar_one_or_none()

        # Auto notes
        notes = (
            f"{len(wins)}W / {len(losses)}L / {len(expired)}E — "
            f"Win rate: {win_rate:.0f}%. "
            f"P&L: {total_pnl:+.2f} pts. "
            f"Symbols: {', '.join(symbols_traded)}."
        )
        if losses:
            # Top loss category
            cats = [p.loss_category for p in losses if p.loss_category]
            if cats:
                from collections import Counter
                top_cat = Counter(cats).most_common(1)[0]
                notes += f" Top loss: {top_cat[0]} ({top_cat[1]}x)."

        journal = DailyJournal(
            date=journal_date,
            total_trades=len(closed_today),
            wins=len(wins),
            losses=len(losses),
            expired=len(expired),
            win_rate=round(win_rate, 1),
            total_pnl=round(total_pnl, 2),
            best_trade_pnl=round(max(pnls), 2) if pnls else 0,
            worst_trade_pnl=round(min(pnls), 2) if pnls else 0,
            avg_confidence=round(sum(confidences) / len(confidences), 3) if confidences else 0,
            avg_rr=round(sum(rr_ratios) / len(rr_ratios), 2) if rr_ratios else 0,
            symbols_traded=symbols_traded,
            regime_breakdown=regime_breakdown,
            learning_version=active_state.version if active_state else 1,
            notes=notes,
        )
        db.add(journal)
        await db.commit()

        logger.info(
            "daily_journal_created",
            date=str(journal_date),
            trades=journal.total_trades,
            win_rate=f"{win_rate:.0f}%",
            pnl=f"{total_pnl:+.2f}",
        )
