"""initial_schema

Revision ID: fbfec7b09376
Revises: 
Create Date: 2026-02-25 21:03:32.791839
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbfec7b09376'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.Enum('FOREX', 'CRYPTO', 'COMMODITY', 'INDEX', 'EQUITY', name='markettype'), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('quote_currency', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tick_size', sa.String(length=20), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index('ix_assets_market_type', 'assets', ['market_type'], unique=False)
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TRADER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'TRIGGERED', 'EXPIRED', name='alertstatus'), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('max_triggers_per_day', sa.Integer(), nullable=False),
    sa.Column('is_repeating', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('cot_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('cftc_contract_code', sa.String(length=20), nullable=True),
    sa.Column('commercial_long', sa.Float(), nullable=False),
    sa.Column('commercial_short', sa.Float(), nullable=False),
    sa.Column('commercial_net', sa.Float(), nullable=False),
    sa.Column('noncommercial_long', sa.Float(), nullable=False),
    sa.Column('noncommercial_short', sa.Float(), nullable=False),
    sa.Column('noncommercial_net', sa.Float(), nullable=False),
    sa.Column('nonreportable_long', sa.Float(), nullable=True),
    sa.Column('nonreportable_short', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('open_interest_change', sa.Float(), nullable=True),
    sa.Column('net_change_weekly', sa.Float(), nullable=True),
    sa.Column('net_change_pct', sa.Float(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cot_asset_date', 'cot_reports', ['asset_id', 'report_date'], unique=True)
    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.Enum('OBV', 'AD_LINE', 'VOLUME_SPIKE', 'ACCUMULATION', 'DISTRIBUTION', 'DIVERGENCE', 'SUPPLY_ZONE', 'DEMAND_ZONE', 'RELATIVE_STRENGTH', 'ATR', 'RSI', 'VWAP', 'ORDERBOOK_IMBALANCE', 'ML_REVERSAL_PROB', name='indicatortype'), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('secondary_value', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indval_asset_type_tf_ts', 'indicator_values', ['asset_id', 'indicator_type', 'timeframe', 'timestamp'], unique=True)
    op.create_table('ohlcv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.Enum('M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1', 'MN1', name='timeframe'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('tick_volume', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ohlcv_asset_tf_ts', 'ohlcv_data', ['asset_id', 'timeframe', 'timestamp'], unique=True)
    op.create_index('ix_ohlcv_timestamp', 'ohlcv_data', ['timestamp'], unique=False)
    op.create_table('onchain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('WHALE_TRANSFER', 'EXCHANGE_INFLOW', 'EXCHANGE_OUTFLOW', 'LARGE_TX', 'CONTRACT_CALL', 'MINT', 'BURN', name='onchaineventtype'), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('address_from', sa.String(length=100), nullable=True),
    sa.Column('address_to', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('chain', sa.String(length=20), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onchain_asset_ts', 'onchain_events', ['asset_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_onchain_events_tx_hash'), 'onchain_events', ['tx_hash'], unique=False)
    op.create_index('ix_onchain_type_ts', 'onchain_events', ['event_type', 'timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('risk_pct', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('setup_notes', sa.Text(), nullable=True),
    sa.Column('exit_notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_asset_id'), 'trades', ['asset_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('WEBSOCKET', 'EMAIL', 'SMS', 'PUSH', 'WEBHOOK', name='alertchannel'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_alert_id'), 'alert_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_history_user_id'), 'alert_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_history_user_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_asset_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_onchain_type_ts', table_name='onchain_events')
    op.drop_index(op.f('ix_onchain_events_tx_hash'), table_name='onchain_events')
    op.drop_index('ix_onchain_asset_ts', table_name='onchain_events')
    op.drop_table('onchain_events')
    op.drop_index('ix_ohlcv_timestamp', table_name='ohlcv_data')
    op.drop_index('ix_ohlcv_asset_tf_ts', table_name='ohlcv_data')
    op.drop_table('ohlcv_data')
    op.drop_index('ix_indval_asset_type_tf_ts', table_name='indicator_values')
    op.drop_table('indicator_values')
    op.drop_index('ix_cot_asset_date', table_name='cot_reports')
    op.drop_table('cot_reports')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.drop_index('ix_assets_market_type', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
